import './globals.css'
import { Fira_Sans_Condensed, Poppins } from 'next/font/google'


const fira_sans_condensed = Fira_Sans_Condensed({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-fira-sans-condensed',
  weight: '800'
})

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: '600'
})


export const metadata = {
  title: 'Kevins Unique Touch',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fira_sans_condensed.variable} ${poppins.variable}`}>{children}</body>
    </html>
  )
}